import java.math.BigInteger; 
import java.nio.charset.StandardCharsets; 
import java.security.MessageDigest; 
import java.security.NoSuchAlgorithmException; 


class sha { 
	public static byte[] getSHA(String input) throws NoSuchAlgorithmException 
	{ 
		MessageDigest md = MessageDigest.getInstance("SHA-256"); 

		return md.digest(input.getBytes(StandardCharsets.UTF_8)); 
	} 
	
	public static String toHexString(byte[] hash) 
	{ 
		BigInteger number = new BigInteger(1, hash); 

		StringBuilder hexString = new StringBuilder(number.toString(16)); 

		while (hexString.length() < 32) 
		{ 
			hexString.insert(0, '0'); 
		} 

		return hexString.toString(); 
	} 
	public static void main(String args[]) 
	{ 
		try
		{ 
			System.out.println("HashCode Generated by SHA-256 for:");  

			String s = "india"; 
			System.out.println("\n" + s + " : " + toHexString(getSHA(s))); 
		} 
		catch (NoSuchAlgorithmException e) { 
			System.out.println("Exception thrown for incorrect algorithm: " + e); 
		} 
	} 
} 
